name: Build and upload to PyPI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        env:
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_WINDOWS: ${{ runner.arch == 'X64' && 'AMD64' || 'ARM64' }}

      - uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: dist-src
          path: dist/*.tar.gz

  pypy_matrix:
    uses: solaluset/python-version-matrix/.github/workflows/generate.yml@v1.1.0
    with:
      runners: '[
        "ubuntu-latest"
      ]'
      min-version: "3.9"
      implementations: '["PyPy"]'

  test_pypy:
    name: Test package on PyPy
    needs: [pypy_matrix]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJson(needs.pypy_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: >
          pip install . pytest
          && cd tests
          && pytest

  upload_pypi:
    needs: [build_wheels, build_sdist, test_pypy]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
